name = "SINNLS"
uuid = "993b1ac0-07ef-437f-99f0-2b4a2275ea96"
authors = ["Jelena Diakonikolas <jelena@cs.wisc.edu>", "Swati Padmanabhan <pswati@uw.edu>", "Chenghui Li <cli539@wisc.edu>", "Chaobing Song <chaobing.song@wisc.edu>"]
version = "0.1.0"

[deps]
IterativeSolvers = "42fd0dbc-a981-5370-80f2-aaf504508153"
KrylovKit = "0b1a1467-8014-51b9-945f-bf0ae24f4b77"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
IterativeSolvers = "0.9.4"
KrylovKit = "0.9.5"
LinearAlgebra = "1.11.0"
SparseArrays = "1.11.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]